# Generated by Django 3.2 on 2022-08-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=13)),
                ('Date', models.DateField()),
                ('Time', models.CharField(max_length=50)),
                ('ManyPeople', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
    ]
