# Generated by Django 3.2 on 2022-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Date',
            field=models.CharField(max_length=13),
        ),
    ]
