# Generated by Django 3.2 on 2022-09-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_booktable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
