# Generated by Django 3.2 on 2022-09-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Email',
            new_name='CUEmail',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Message',
            new_name='CUMessage',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='CUName',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='Subject',
            new_name='CUSubject',
        ),
    ]
